### PR TITLE
Fixes to account for variable page size

### PR DESCRIPTION
**Pull request by ViktorWalter**
Multiple PDF files I have dealt with were originally displayed with two issues if they had non-uniform page sizes (e.g. large resolution scan of the first page of a scanned book):
1: They were by default zoomed out significantly, such that multiple pages could fit into the view on the default zoom level.
2: They were displayed with large black margins, such that the actual page was small with respect to the view, approximately in the size it has relative to the resolution of the largest page.
This pull request provides changes derived from @ailrk 's fix of the latter issue, expanded to also fix the former.

### CODE REVIEW

**Comment by ViktorWalter** [comment]
I'll look into it.

**Comment by ViktorWalter** [comment]
Ok, I think I've unified the worst offenders. Is it now legible?

**Comment by sebastinas** [comment]
There are still plenty of unrelated changes. The PR seems to revert a bunch of completely unrelated stuff.

**Comment by ViktorWalter** [comment]
I have merged the language files from upstram. Currently, ` git diff ` only lists the relevant files.

**Comment by lambdcalculus** [comment]
Any news on this? It's still ready to merge.

**Comment by sebastinas** [comment]
@ViktorWalter Thanks again … finally merged.

**Pull request closed without merging**
