### PR TITLE
Add GitHub build action

### PR DESCRIPTION
**Pull request by dylanmtaylor**

### CODE REVIEW

**Comment by alerque** [comment]
I'm not sure how much sense a GH action makes for a project primarily hosted on GitLab. You know this repo is just a mirror right? A GitLab CI config might be welcome but this seems out of place.

**Comment by dylanmtaylor** [comment]
> I'm not sure how much sense a GH action makes for a project primarily hosted on GitLab. You know this repo is just a mirror right? A GitLab CI config might be welcome but this seems out of place.

I can make one for GitLab as well if that's desirable

**Comment by alerque** [comment]
I would suggest opening an issue or MR on the GitLab for the upstream to get the maintainer's attention, not here.

Also just a side note when you build anything with Arch Linux it's advisable to start from the base-devel image instead of base. It's bigger but will get cached as a Docker layer and save a lot of network and CI runner time not having to install all the basic deps for building stuff

**Comment by sebastinas** [comment]
Gitlab CI is already being used: https://git.pwmt.org/pwmt/zathura/-/pipelines

**Pull request closed without merging**
