### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by loouu**

### CODE REVIEW

**Comment by alerque** [comment]
This is a mirror. You probably need to submit this to the projects actual git repository which is a self-hosted Gitlab instance. Otherwise it's unlikely to get any traction.

**Comment by loouu** [comment]
Thanks for the tip!

**Comment by strogiyotec** [comment]
Why does this mirror have more stars than original repo ?)

**Comment by alerque** [comment]
@strogiyotec Because this mirror is on Github where reams of developers are already logged in with their accounts, the original upstream repo is a dedicated Gitlab instance that you have to sign up for an account just for the project. Most people won't do that just to star a repo.

**Comment by sebastinas** [comment]
Wouldn't this also require `REAMDE` to be converted to markdown?

**Comment by alerque** [comment]
@sebastinas Did you look at it? It already is written in Markdown.

**Comment by sebastinas** [comment]
It's some pseudo Markdown. The code blocks are not intended by 4 spaces, in `sphinx_rtd_theme`, `rtd` is not supposed to be emphasized, and the link at the end would need to converted.

**Comment by alerque** [comment]
Roger that. The link wouldn't be broken, but the code blocks would need to be fixed. In any case this PR should be closed and a similar one that does this fix should be submitted to the Gitlab repository.

**Comment by sebastinas** [comment]
I also merge PRs on Github.

**Comment by sebastinas** [comment]
Merged and cleaned up.

**Pull request closed without merging**
