### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by skwuent**
Fix a spelling typo in the Makefile

### CODE REVIEW

**Comment by sebastinas** [comment]
Thank you. I've merged it your fix to our develop branch.

**Comment by skwuent** [comment]
Cool. Would it help you out to submit pull requests from a different branch in the future, or is this not neccessary?

Thanks for making this tool. I had been using apvlv and but I think Zathura's development approach is more sustainable.

**Comment by sebastinas** [comment]
We prefer if they are based on the develop branch since that's where they are going to end up. We only merge back to master after a release.

**Comment by skwuent** [comment]
Sorry to break the convention, future pull requests will be on develop.

**Pull request closed without merging**
